workflows:
  android-release:
    name: Application Null - Android Build
    max_build_duration: 30
    environment:
      flutter: stable
      android_signing:
        - application_null_keystore
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
